name: "Assign Reviewers"
on:
  pull_request:
    types: [opened, ready_for_review]

jobs:
  assign-reviewers:
    runs-on: ubuntu-latest
    steps:
      - name: "Assign Team and Persons"
        uses: rowi1de/auto-assign-review-teams@v1.1.3
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          org: "Shift3" #only needed for  pick-one-from-persons-or-team=true
          teams: "pr-team" # only works for GitHub Organisation/Teams
          persons: "" # add individual persons here
          include-draft: false # Draft PRs will be skipped (default: false)
          skip-with-manual-reviewers: 0 # Skip this action, if the number of reviwers was already assigned (default: 0)
          pick-one-from-persons-or-team: true # Will pick out one reviewer from persons and/or the first GitHub team and "org" set (default: false)
