name: Handle Pull Request

on:
  pull_request:
    types: [opened, ready_for_review]

jobs:
  add-reviewers:
    name: "🤖 Auto assign PR reviewers"
    runs-on: ubuntu-latest

    steps:
      - name: "Assign 'pr-team' to PR"
        uses: rowi1de/auto-assign-review-teams@v1.1.3
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          teams: "PR Team"
